title: "FMM"
remote_theme: pmarsceill/just-the-docs
search_enabled: true

url: "https://fmm-wiki.github.io"
footer_content: "Copyright &copy; 2020 Can Yang. Distributed by an <a href=\"https://github.com/cyang-kth/fmm/blob/master/LICENSE.TXT\">Apache License.</a>"

logo: "/assets/images/fmm.png"

heading_anchors: true

# Aux links for the upper right navigation

github_url: "//github.com/cyang-kth/fmm"
github_stars_url: "https://img.shields.io/github/stars/cyang-kth/fmm?logo=GITHUB&style=social"

wiki_repo_name: "fmm-wiki"
wiki_repo_url: "//github.com/fmm-wiki/fmm-wiki.github.io"

ga_tracking: UA-109047723-2
