title: "FMM-wiki"
remote_theme: pmarsceill/just-the-docs
search_enabled: true

url: "https://fmm-wiki.github.io"
footer_content: "Copyright &copy; 2020 Can Yang. Distributed by an <a href=\"https://github.com/cyang-kth/fmm/blob/master/LICENSE.TXT\">Apache License.</a>"

# logo: "/assets/images/fmm.png"

heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "FMM on GitHub":
    - "//github.com/cyang-kth/fmm"
